# global settings
title: "Glassman Lab @ Harvard SEAS"
description: "augmenting human intelligence with computation" #description: "Making communicating with computers more accessible: easier, faster, and safer"
#url: "pl-hci-seminar.seas.harvard.edu" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from
